services:
  - type: web
    name: driveailane
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --prefer-binary -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONUNBUFFERED
        value: true
      - key: PIP_PREFER_BINARY
        value: true
      - key: RENDER
        value: true
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 