services:
  - type: web
    name: driveailane
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONUNBUFFERED
        value: true 